import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import CartProvider from "@/components/Provider";
import ShoppingCartModel from "@/components/ShoppingCartModel";
import Footer from "@/components/Footer";

const font = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} ${font.className} antialiased`}>
        <CartProvider>
          <Navbar />
          <ShoppingCartModel/>
          {children}
          <Footer/>
        </CartProvider>
      </body>
    </html>
  );
}
